version: '3.5'
services:
  wetty:
    container_name: wetty
    image: wettyoss/wetty
    #    build:
    #  context: .
    #  dockerfile: containers/wetty/Dockerfile
    tty: true
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    environment:
      SSHHOST: 'wetty-ssh'
      SSHPORT: 22
      NODE_ENV: 'development'

  web:
    image: nginx
    container_name: wetty-web
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx.template:/etc/nginx/conf.d/wetty.template
    ports:
      - '3179:80'
    environment:
      - NGINX_DOMAIN=sh.daghlani.ir
      - NGINX_PORT=80
      - WETTY_HOST=wetty
      - WETTY_PORT=3000
    command: >-
      /bin/bash -c "envsubst
      '$${NGINX_DOMAIN},$${NGINX_PORT},$${WETTY_HOST},$${WETTY_PORT}' <
      /etc/nginx/conf.d/wetty.template > /etc/nginx/conf.d/default.conf && nginx
      -g 'daemon off;'"

  wetty-ssh:
    container_name: wetty-ssh
    build:
      context: .
      dockerfile: Dockerfile
    image: wettyoss/wetty:ssh-ali
      #image: wettyoss/wetty:ssh

networks:
  default:
    name: wetty
